name: Review Pipeline

on:
  pull_request:
    branches:
      - "**"

jobs:
  tofu-plan:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT }}:role/gh-actions
          role-session-name: JohnWww_${{ github.run_id }}_${{ github.run_attempt }}
      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@v1
      - name: Build
        run: pnpm build
      - name: Initialize OpenTofu
        run: tofu -chdir=infra init
      - name: Plan infrastructure changes
        run: tofu -chdir=infra plan -var="aws_region=${{ secrets.AWS_REGION }}"

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Lint
        run: pnpm lint
